VPATH= .:../boitho-bbdn/:../common/:../base64/:../maincfg/:../crawlManager/:../key:.

CFLAGS=		

CGIBIN=		true

WANT_LIBCONFIG=	true
WANT_MYSQL=	true
WANT_BASE64=	true
WANT_COMMON=	true
WANT_LIBXML=	true

OBJS=	main.o bbdnclient.o daemon.o base64.o maincfg.o client.o key.o
PROG=	bbdocumentWebAdd

include ../../mk/prog.mk
