/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <pthread.h>
#include <errno.h>

#include "suggest.h"
#include "../suggest/suggest.h"

pthread_mutex_t    mutex = PTHREAD_MUTEX_INITIALIZER;
struct suggest_data *sd = NULL;

#if 0
bool_t
get_best_results_1_svc(char **argp, namenode *result, struct svc_req *rqstp)
{
	bool_t retval;
	/*
	namelist nl;
	namelist *nlp;
	*/
	int i = 5;
	struct suggest_input **si;

	if (pthread_mutex_lock(&mutex) != 0) {
#if 0
		result->_errno = errno;
#endif
		return TRUE;
	}
	if (sd == NULL) {
		sd = suggest_init();
		if (sd == NULL)
			return FALSE;
		suggest_read_frequency(sd, "../suggest/UnikeTermerMedForekomst.ENG");
		suggest_most_used(sd);
	}
	if (pthread_mutex_unlock(&mutex) != 0) {
		/*
		result->_errno = errno;
		*/
		return TRUE;
	}

	printf("Argument: %s\n", *argp);
#if 0
	nlp = &result->numbest_res_u.list;
	for (si = suggest_find_prefix(sd, *argp);
	     *si != NULL;
	     si++) {
		nl = *nlp = (namenode *)
			malloc(sizeof(namenode));
		if (nl == NULL) {
			result->_errno = errno;
			return TRUE;
		}
		nl->name = strdup((*si)->word);
		nl->frequency = (*si)->frequency;
		nlp = &nl->next;
	}

	*nlp = (namelist)NULL;
	result->_errno = 0;
#endif
	si = suggest_find_prefix(sd, *argp);
	result->name = strdup((*si)->word);
	result->frequency = (*si)->frequency;


	return TRUE;
}
#endif
#if 1

/*
 * XXX: Only on caller can be in get_best_results_1_svc at a time?
 */

numbest_res *
get_best_results_1_svc(char **argp, struct svc_req *rqstp)
{
	bool_t retval;
	namelist nl;
	namelist *nlp;
	static  numbest_res result;
	static int called = 0;
	int i = 5;
	struct suggest_input **si;

#if 0
	if (pthread_mutex_lock(&mutex) != 0) {
		result._errno = errno;
		return &result;
	}
#endif

	if (sd == NULL) {
		sd = suggest_init();
		if (sd == NULL)
			return &result;
		suggest_read_frequency(sd, "../suggest/UnikeTermerMedForekomst.ENG");
		suggest_most_used(sd);
	}

	if (called == 1) {
		xdr_free(xdr_numbest_res, &result);
	}

	printf("Argument: %s\n", *argp);
	called = 1;
#if 1
	nlp = &result.numbest_res_u.list;
	for (si = suggest_find_prefix(sd, *argp);
	     si != NULL && *si != NULL;
	     si++) {
		nl = *nlp = (namenode *)
			malloc(sizeof(namenode));
		if (nl == NULL) {
			result._errno = errno;
			return &result;
		}
		nl->name = strdup((*si)->word);
		nl->frequency = (*si)->frequency;
		nlp = &nl->next;
	}

	*nlp = (namelist)NULL;
	result._errno = 0;
#else
	si = suggest_find_prefix(sd, *argp);
	result->name = strdup((*si)->word);
	result->frequency = (*si)->frequency;
#endif
#if 0
	if (pthread_mutex_unlock(&mutex) != 0) {
		result._errno = errno;
		return &result;
	}
#endif
	return &result;
}
#endif

#if 0
namenode *
get_best_results_1_svc(char **argp, struct svc_req *rqstp)
{
        static namenode  result;


	result.name = strdup("hei");
	result.frequency = 1000;

        return &result;
}
#endif


#if 0
int
suggest_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
#endif

