#!/bin/sh
#
# chkconfig: 345 99 10
# description: Starts and stops the Boitho Daemon searchdbb.
# processname: tlcd
# Tyan LCD Daemon


# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 0
fi



tlcdname=tlcd
TARGETDIR=/usr/bin/tyan/tlcd


RETVAL=0
start() {
	echo -n $"Starting $tlcdname: "
        $TARGETDIR/$tlcdname
	RETVAL=$?
	echo
	return $RETVAL
}

stop() {
	echo -n $"Stopping $tlcdname: "
	killproc $tlcdname
	RETVAL=$?
	echo
	return $RETVAL
}

restart(){
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  status)
	status $tlcdname
	RETVAL=$?
        ;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	RETVAL=1
esac

exit $RETVAL
