#!/bin/bash

PREFIX=`echo "$0" | sed -e "s|[^/]*$||"`
GET_REL=`echo "$PREFIX""get_rel"`
WASH_TAGS=`echo "$PREFIX""wash_tags"`
XSL=`echo "$PREFIX""xlml2xhtml.xsl"`

WORKSHEETS=`unzip -p "$1" xl/_rels/workbook.xml.rels | $GET_REL --worksheets`

echo "<html><body>"

for worksheet in $WORKSHEETS; do
    unzip -p "$1" xl/$worksheet | $WASH_TAGS | xsltproc $XSL - | sed -ne "2,\$p"
    echo "<hr />"
done

echo "</body></html>"
