/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <pthread.h>
#include <errno.h>

#include "suggest.h"
#include "../suggest/suggest.h"

pthread_mutex_t    mutex = PTHREAD_MUTEX_INITIALIZER;
struct suggest_data *sd = NULL;

bool_t
get_best_results_1_svc(char **argp, numbest_res *result, struct svc_req *rqstp)
{
	bool_t retval;
	namelist nl;
	namelist *nlp;
	int i = 5;
	struct suggest_input **si;

	if (pthread_mutex_lock(&mutex) != 0) {
		result->_errno = errno;
		return TRUE;
	}
	if (sd == NULL) {
		sd = suggest_init();
		if (sd == NULL)
			return FALSE;
		suggest_read_frequency(sd, "../../meta/UnikeTermerMedForekomst.ENG");
		suggest_most_used(sd);
	}
	if (pthread_mutex_unlock(&mutex) != 0) {
		result->_errno = errno;
		return TRUE;
	}

	printf("Argument: %s\n", *argp);
	nlp = &result->numbest_res_u.list;
	for (si = suggest_find_prefix(sd, *argp);
	     *si != NULL;
	     si++) {
		nl = *nlp = (namenode *)
			malloc(sizeof(namenode));
		if (nl == NULL) {
			result->_errno = errno;
			return TRUE;
		}
		nl->name = strdup((*si)->word);
		nl->frequency = (*si)->frequency;
		nlp = &nl->next;
	}

	*nlp = (namelist)NULL;
	result->_errno = 0;

	return TRUE;
}

int
suggest_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
