/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suggest.h"


void
suggest_1(char *host, char *arg)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	numbest_res result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, SUGGEST, SUGGESTVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = get_best_results_1(&arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	else {
		if (result_1._errno == 0) {
			namelist nl;

			for (nl = result_1.numbest_res_u.list;
			     nl != NULL;
			     nl = nl->next) {
				printf("Name: %s/%d\n", nl->name, nl->frequency);
			}
		}
		else {
			printf("error...\n");
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host arg\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	suggest_1 (host, argv[2]);
exit (0);
}
