#!/bin/bash

echo -n "Searchdaimon ES running on " > /etc/issue
cat /etc/system-release >> /etc/issue
echo "Kernel \r on an \m" >> /etc/issue
echo -n "IP-" >> /etc/issue
ifconfig eth1|sed -ne "2p"|awk '{print $2}' >> /etc/issue
echo >> /etc/issue
