#!/bin/bash

PREFIX=`echo "$0" | sed -e "s|[^/]*$||"`
GET_REL=`echo "$PREFIX""get_rel"`
XSL=`echo "$PREFIX""wordml2xhtml.xsl"`

unzip -p "$1" word/document.xml | xsltproc $XSL -

# Embeddings:

EMBEDDINGS=`unzip -p "$1" word/_rels/document.xml.rels | $GET_REL --package`

TMP=`mktemp /tmp/ooxml_tools.XXXXXX`

for embedding in $EMBEDDINGS; do
    RUN=""

    LEN=`echo $embedding|wc -c`
    LEN=`expr $LEN - 5`
    POSTFIX=`echo $embedding|cut -b $LEN-`
    if [[ "$POSTFIX" == ".docx" ]]; then
	RUN=`echo "$PREFIX""docx2html"`
    elif [[ "$POSTFIX" == ".xlsx" ]]; then
	RUN=`echo "$PREFIX""xlsx2html"`
    elif [[ "$POSTFIX" == ".pptx" ]]; then
	RUN=`echo "$PREFIX""pptx2html"`
    fi

    if [[ "$RUN" != "" ]]; then
	unzip -p "$1" "word/$embedding" > $TMP
	echo "<hr />"
	$RUN $TMP
    fi
done

rm $TMP
