#!/bin/bash

PREFIX=`echo "$0" | sed -e "s|[^/]*$||"`
GET_REL=`echo "$PREFIX""get_rel"`
WASH_TAGS=`echo "$PREFIX""wash_tags"`
XSL=`echo "$PREFIX""xlml2xhtml.xsl"`

unzip -p "$1" xl/sharedStrings.xml | sed -e "s/<[^>]*>\(<[^>]*>\)*/ <span>/g"

WORKSHEETS=`unzip -p "$1" xl/_rels/workbook.xml.rels | $GET_REL --worksheets`

#echo "<html><body>"

for worksheet in $WORKSHEETS; do
    echo "<hr />"
    unzip -p "$1" xl/$worksheet | $WASH_TAGS | xsltproc $XSL - | sed -ne "2,\$p"
done

# Embeddings:

EMBEDDINGS=`unzip -p "$1" xl/_rels/workbook.xml.rels | $GET_REL --package`

TMP=`mktemp /tmp/ooxml_tools.XXXXXX`

for embedding in $EMBEDDINGS; do
    RUN=""

    LEN=`echo $embedding|wc -c`
    LEN=`expr $LEN - 5`
    POSTFIX=`echo $embedding|cut -b $LEN-`
    if [[ "$POSTFIX" == ".docx" ]]; then
	RUN=`echo "$PREFIX""docx2html"`
    elif [[ "$POSTFIX" == ".xlsx" ]]; then
	RUN=`echo "$PREFIX""xlsx2html"`
    elif [[ "$POSTFIX" == ".pptx" ]]; then
	RUN=`echo "$PREFIX""pptx2html"`
    fi

    if [[ "$RUN" != "" ]]; then
	unzip -p "$1" "xl/$embedding" > $TMP
	echo "<hr />"
	$RUN $TMP
    fi
done

rm $TMP

#echo "</body></html>"
