/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suggest.h"


void
messageprog_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	suggestions result_1;
	char *printmessage_1_user;
	char *printmessage_1_query;
	stringtable  printmessage_1_arg3;

#ifndef	DEBUG
	clnt = clnt_create (host, MESSAGEPROG, MESSAGEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = printmessage_1(printmessage_1_user, printmessage_1_query, printmessage_1_arg3, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	messageprog_1 (host);
exit (0);
}
