/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux bbh-001.boitho.com 2.4.22-pre6 #2 SMP Tue Jul 15 17:03:49 CEST 2003 i686 unknown"
#define BUILD_ENV_DATE "Thu Aug  9 16:59:05 CEST 2007"
#define BUILD_ENV_SRCDIR "/home/boitho/src/samba-3.0.25b/source"
#define BUILD_ENV_BUILDDIR "/home/boitho/src/samba-3.0.25b/source"
#define BUILD_ENV_USER "boitho"
#define BUILD_ENV_HOST "bbh-001.boitho.com"
#define BUILD_ENV_COMPILER "gcc"
#endif /* _BUILD_ENV_H */
