/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include <stdio.h>

#include "../suggestrpc/suggest.h"

#include "../cgi-util/cgi-util.h"

void
suggest_1(char *host, char *arg, char *user)
{
	CLIENT *clnt;
	numbest_res *result_1;
	struct senddata args;

	args.word = arg;
	args.user = user;

#ifndef	DEBUG
	clnt = clnt_create (host, SUGGEST, SUGGESTVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	/* XXX: set lower timeout */
	result_1 = get_best_results_2(&args, clnt);
        printf("Content-type: text/plain\n\n");
	if (!result_1) {
#if 1
		//clnt_perror (clnt, "call failed");
#endif
	}
	else {
		if (result_1->_errno == 0) {
			namelist nl;
			//int i = 0;
			//printf("Content-type: text/html\n\n");
			for (nl = result_1->numbest_res_u.list;
			     nl != NULL;
			     nl = nl->next) {
				printf("%s\n", nl->name);
                        }
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

#define RPC_HOST "localhost"

int
main (int argc, char *argv[])
{
	char *host = NULL;
	char *prefix;
	char *user;
	int ret;

	if (getenv("QUERY_STRING")) {
		// We are in CGI mode
		if ((ret = cgi_init()) != CGIERR_NONE) {
			fprintf(stderr, "Error # %d: %s.\n", ret, cgi_strerror(ret));
			exit(0);
		}
		if ((prefix = cgi_getentrystr("q")) == NULL) {
			fprintf(stderr, "Did not find a prefix.\n");
			exit(0);
		}
		user = getenv("REMOTE_USER");
		if (user == NULL) {
			printf("Content-type: text/plain\n\n");
			printf("Not logged in.\n");
			exit(0);
		}
	}
	else {
		if (argc < 4) {
			printf("Usage: ./prog host prefix user\n");
			exit(1);
		}
		host = argv[1];
		prefix = argv[2];
		user = argv[3];
	}

	if (host == NULL)
		host = RPC_HOST;
	suggest_1 (host, prefix, user);

	return 0;
}
