/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include <stdio.h>

#include "../suggestrpc/suggest.h"

#include "../cgi-util/cgi-util.h"

void
suggest_1(char *host, char *arg)
{
	CLIENT *clnt;
	numbest_res *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, SUGGEST, SUGGESTVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	/* XXX: set lower timeout */
	result_1 = get_best_results_1(&arg, clnt);
	if (!result_1) {
#if 1
		printf("Content-type: text/html\n\n");
		//clnt_perror (clnt, "call failed");
#endif
	}
	else {
		if (result_1->_errno == 0) {
			namelist nl;
			int i = 0;
			printf("Content-type: text/html\n\n");
			for (nl = result_1->numbest_res_u.list;
			     nl != NULL;
			     nl = nl->next) {
				printf("<div class=\"internalsuggest\" id=\"is%d\""
				" onmouseover=\"highlightobj(this);\""
				">\n",
				i++);
				printf("%s\n",
				       nl->name);//, nl->frequency);
				printf("</div>\n");
			}
		}
		else {
			printf("Content-type: text/html\n\n");
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

#define RPC_HOST "localhost"

int
main (int argc, char *argv[])
{
	char *host = NULL;
	char *prefix;
	int ret;

	if (getenv("QUERY_STRING")) {
		// We are in CGI mode
		if ((ret = cgi_init()) != CGIERR_NONE) {
			fprintf(stderr, "Error # %d: %s.\n", ret, cgi_strerror(ret));
			exit(0);
		}
		if ((prefix = cgi_getentrystr("prefix")) == NULL) {
			fprintf(stderr, "Did not find a prefix.\n");
			exit(0);
		}
	}
	else {
		if (argc < 3) {
			printf("Usage: ./prog host prefix\n");
			exit(1);
		}
		host = argv[1];
		prefix = argv[2];
	}

	if (host == NULL)
		host = RPC_HOST;
	suggest_1 (host, prefix);

	return 0;
}
