#!/bin/sh
#
# chkconfig: 345 85 10
# description: Starts the boitho database setup utility
# processname: boithodbsetup


# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 0
fi

if [ "$BOITHOHOME" == "" ]; then
    export BOITHOHOME=/home/boitho/boithoTools
fi
# Byttes ut:
#B_RUN="/usr/local/sbin/daemonize $BOITHOHOME/bin/everrun $BOITHOHOME/bin/searchdbb localhost"
B_RUN="/usr/local/sbin/daemonize /bin/sh $BOITHOHOME/blackbox/boithodbsetup"
B_NAME=boithodbsetup
RETVAL=0

start() {
	echo -n $"Starting Boitho Daemon "$B_NAME"."
	daemon $B_RUN
	RETVAL=$?
	echo
	return $RETVAL
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	;;
  restart)
  	;;
  status)
	pids=`pidof $BOITHOHOME/bin/everrun`
	if [ "$pids" == "" ]; then
	    pid=""
	else
	    pid=`ps -o pid,args -w -p $pids|grep $B_NAME|awk '{ printf("%s ", $1); }'`
	fi
	pid2=`pidof $BOITHOHOME/blackbox/$B_NAME`
	pid="$pid $pid2"
	if [ "$pid" == " " ] ; then pid=""; fi
	base=$B_NAME

	if [ "$pid" != "" ] ; then
	        echo $"${base} (pid $pid) is running..."
	else
		echo $"${base} is stopped"
	fi
	;;
  *)
	echo $"Usage: $0 {start|status}"
	exit 1
esac

exit $?
