#!/bin/sh
# Startup script for everrun
#
# chkconfig: 2345 20 80
# description: Configure /proc so that cores are dumped to the right place

# Source function library.
. /etc/rc.d/init.d/functions

start() {
	echo /coredumps/core.%p > /proc/sys/kernel/core_pattern 
	return 0
}

stop() {
	return 0
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;
	*)
	    echo $"Usage: $0 {start|stop}"
	    exit 1

esac

exit $RETVAL
